2021-05-07 12:01:46,404 DEBUG    root            Loaded Command Group: ['gcloud', 'secrets']
2021-05-07 12:01:46,405 DEBUG    root            Loaded Command Group: ['gcloud', 'secrets', 'versions']
2021-05-07 12:01:46,408 DEBUG    root            Loaded Command Group: ['gcloud', 'secrets', 'versions', 'access']
2021-05-07 12:01:46,416 DEBUG    root            Running [gcloud.secrets.versions.access] with arguments: [--secret: "windows-password", VERSION: "1"]
2021-05-07 12:01:46,435 WARNING  root            Could not open the configuration file: [/home/dwijeshm3/.config/gcloud/configurations/config_default].
2021-05-07 12:01:46,437 DEBUG    root            (gcloud.secrets.versions.access) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 982, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/secrets/versions/access.py", line 56, in Run
    return secrets_api.Versions().Access(version_ref)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/secrets/api.py", line 244, in __init__
    super(Versions, self).__init__(client, messages)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/secrets/api.py", line 71, in __init__
    self.client = client or GetClient()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/secrets/api.py", line 29, in GetClient
    apis.ResolveVersion('secretmanager'))
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 314, in GetClientInstance
    CheckResponseForApiEnablement())
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 167, in _GetClientInstance
    response_encoding=transport.ENCODING)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/transports.py", line 87, in GetApitoolsTransport
    streaming_response_body=streaming_response_body)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/requests.py", line 80, in GetSession
    allow_account_impersonation, True)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/requests.py", line 115, in WrapQuota
    use_google_auth)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/transport.py", line 53, in QuotaProject
    creds = store.LoadIfEnabled(allow_account_impersonation, use_google_auth)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 564, in LoadIfEnabled
    use_google_auth=use_google_auth)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 667, in Load
    cred = _Load(account, scopes, prevent_refresh, use_google_auth)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 749, in _Load
    named_configs.ActiveConfig(False).file_path)
googlecloudsdk.core.credentials.store.NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2021-05-07 12:01:46,438 ERROR    root            (gcloud.secrets.versions.access) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
